{{- with .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
