name: Lint

on:
  push:
    branches:
      - main
    paths-ignore: &common_ignores
      - '.github/workflows/docker.yml'
      - '.github/workflows/helm.yml'
      - '.github/dependabot.yml'
      - 'helm/**'
      - '.env.example'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore: *common_ignores

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          only-new-issues: true
