name: Test

on:
  push:
    branches:
      - main
    paths: &common_paths
      - '.github/workflows/test.yml'
      - 'cmd'
      - 'internal'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths: *common_paths

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          only-new-issues: true

      - name: Test
        run: go test ./... -v -race -cover -count=1
